# Enable True color support
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Mouse support
set -g mouse on

# Split bindings
unbind %
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
bind | split-window -h -c "#{pane_current_path}"

# Tmux plugin manager
set-environment -g TMUX_PLUGIN_MANAGER_PATH ~/.config/tmux/.tmux/plugins
set -g @plugin 'tmux-plugins/tpm' # must be the first plugin
set -g @plugin 'catppuccin/tmux'

# Configure Catppuccin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_status_background "none"
set -g @catppuccin_window_status_style "none"
set -g @catppuccin_pane_status_enabled "off"
set -g @catppuccin_pane_border_status "off"

# Status left
set -g status-left-length 100
set -g status-left ""
set -ga status-left "#{?client_prefix,#{#[bg=#{@thm_red},fg=#{@thm_bg},bold] \uebc8 #S },#{#[bg=#{@thm_bg},fg=#{@thm_green}] \uebc8 #S }}"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_overlay_0},none]#{?window_zoomed_flag,│,}"
set -ga status-left "#[bg=#{@thm_bg},fg=#{@thm_yellow}]#{?window_zoomed_flag, zoom ,}"

# Status right
set -g status-right-length 100
set -g status-right ""
set -ga status-right "#[bg=#{@thm_bg},fg=#{@thm_green}] %H:%M "
set -ga status-right "#[bg=#{@thm_bg},fg=#{@thm_overlay_0}]│"
set -ga status-right "#[bg=#{@thm_bg},fg=#{@thm_mauve}] %d-%b-%y "

# Configure Tmux
set -g status-position bottom
set -g status-style "bg=#{@thm_bg}"
set -g status-justify "absolute-centre"

# Window
set -wg automatic-rename on
set -g automatic-rename-format "#{pane_current_command}"
set -g window-status-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-style "bg=#{@thm_bg},fg=#{@thm_overlay_0}"
set -g window-status-last-style "bg=#{@thm_bg},fg=#{@thm_overlay_1}"
set -g window-status-activity-style "bg=#{@thm_red},fg=#{@thm_bg}"
set -g window-status-bell-style "bg=#{@thm_red},fg=#{@thm_bg},bold"
set -gF window-status-separator "#[bg=#{@thm_bg},fg=#{@thm_overlay_0}]│"
set -g window-status-current-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-current-style "bg=#{@thm_blue},fg=#{@thm_bg},bold"

run '~/.config/tmux/.tmux/plugins/tpm/tpm' # always keep this line last
